import React, {useEffect, useState} from "react";
import {connect} from "react-redux";
import {Link} from "react-router-dom";

import {
    LikeOutlined,
    DislikeOutlined,
    PlusOutlined,
    ShareAltOutlined,
    CaretUpOutlined,
    CaretDownOutlined,
    LockOutlined,
} from '@ant-design/icons';

import {Spin} from 'antd';

import ShareContainer from "../../Layout/components/Share/Share";

import "./Details.less"

const Details = (props) => {
    const { setVideoDetailsData } = props;
    const [spinning, setSpinning] = useState(true);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [episode, setEpisode] = useState(true);
    const [pageData, setPageData] = useState();
    const [pageDataLock, setPageDataLock] = useState();
    const [coverImage, setCoverImage] = useState();

    const handleShowModal = () => {
        setIsModalOpen(true);
    };
    const HandleEpisodesRouterTo = (key, saleType) => {
        // if(saleType == 4) return;
        // "/video?gid=" + (index + 1)
        window.location.href = window.location.origin + "/video?gid=" + key;
    }
    const switchEpisode = () => {
        setEpisode(!episode)
    };
    const getNum = (str) => {
        let newstr = String(str)
        return newstr.substring(0, 1) + "." + newstr.substring(1, 3) + "W+"
    }

    function fetchData() {
        return new Promise((resolve, reject) => {
            // 模拟异步操作
            setTimeout(() => {
                const data = {
                    "code": 200,
                    "msg": null,
                    "data": {
                        "id": 676,
                        "title": "Love's Promotion: From Boss to Hubby",
                        "coverUrl": "https://res.net-goal.com/video/loves_promotion_from_boss_to_hubby/1.png",
                        "dramaCoverUrl": "",
                        "saleType": 4,
                        "play": "other",
                        "state": "finish",
                        "cv": "Love's Promotion: From Boss to Hubby\" is a contemporary romance novel that explores the unexpected journey of two individuals who start off as boss and employee but eventually find love and develop a meaningful relationship. The story revolves around the protagonist, Emma, who initially views her boss, David, as nothing more than a strict and distant authority figure. However, as they work together on projects and spend more time in each other's company, they discover common interests, shared values, and an underlying attraction. As Emma and David navigate the complexities of their professional and personal lives, they find themselves drawn closer to each other. They develop a deep emotional connection, fueled by their mutual respect and admiration. However, they must deal with the challenges of maintaining a secret office romance and the potential conflicts it may create. Throughout the story, \"Love's Promotion: From Boss to Hubby\" explores themes of professional boundaries, trust, and the power of love. It delves into the complexities of work-life balance and the sacrifices both individuals must make to pursue their relationship.The novel takes readers on a rollercoaster of emotions as Emma and David's love story unfolds. It showcases the growth of their relationship, the challenges they face, and the eventual realization that they cannot imagine their lives without each other.",
                        "authVip": 0,
                        "author": "",
                        "intro": "Love's Promotion: From Boss to Hubby\" is a contemporary romance novel that explores the unexpected journey of two individuals who start off as boss and employee but eventually find love and develop a meaningful relationship. The story revolves around the protagonist, Emma, who initially views her boss, David, as nothing more than a strict and distant authority figure. However, as they work together on projects and spend more time in each other's company, they discover common interests, shared values, and an underlying attraction. As Emma and David navigate the complexities of their professional and personal lives, they find themselves drawn closer to each other. They develop a deep emotional connection, fueled by their mutual respect and admiration. However, they must deal with the challenges of maintaining a secret office romance and the potential conflicts it may create. Throughout the story, \"Love's Promotion: From Boss to Hubby\" explores themes of professional boundaries, trust, and the power of love. It delves into the complexities of work-life balance and the sacrifices both individuals must make to pursue their relationship.The novel takes readers on a rollercoaster of emotions as Emma and David's love story unfolds. It showcases the growth of their relationship, the challenges they face, and the eventual realization that they cannot imagine their lives without each other.",
                        "isCollect": 0,
                        "isPurchase": 0,
                        "readTotal": 19488,
                        "collectTotal": 0,
                        "commentTotal": 0,
                        "isShelf": 1,
                        "packageDiscount": 100,
                        "packageType": 0,
                        "packagePrice": 0,
                        "tagList": [
                            {
                                "id": 10,
                                "tag": "爱情"
                            },
                            {
                                "id": 21,
                                "tag": "言情"
                            },
                            {
                                "id": 22,
                                "tag": "现代"
                            },
                            {
                                "id": 6,
                                "tag": "重生"
                            }
                        ],
                        "dramaList": [
                            {
                                "id": 57110,
                                "worksId": 676,
                                "number": 1,
                                "title": "001",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 1,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 0,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 225,
                                "playCount": 1,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57111,
                                "worksId": 676,
                                "number": 2,
                                "title": "002",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 1,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 0,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 95,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57112,
                                "worksId": 676,
                                "number": 3,
                                "title": "003",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 1,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 0,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 97,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57113,
                                "worksId": 676,
                                "number": 4,
                                "title": "004",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 1,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 0,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 82,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57114,
                                "worksId": 676,
                                "number": 5,
                                "title": "005",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 1,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 0,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 99,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57115,
                                "worksId": 676,
                                "number": 6,
                                "title": "006",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 71,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57116,
                                "worksId": 676,
                                "number": 7,
                                "title": "007",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 95,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57117,
                                "worksId": 676,
                                "number": 8,
                                "title": "008",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 73,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57118,
                                "worksId": 676,
                                "number": 9,
                                "title": "009",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 103,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57119,
                                "worksId": 676,
                                "number": 10,
                                "title": "010",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57120,
                                "worksId": 676,
                                "number": 11,
                                "title": "011",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 95,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57121,
                                "worksId": 676,
                                "number": 12,
                                "title": "012",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 73,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57122,
                                "worksId": 676,
                                "number": 13,
                                "title": "013",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 103,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57123,
                                "worksId": 676,
                                "number": 14,
                                "title": "014",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57124,
                                "worksId": 676,
                                "number": 15,
                                "title": "015",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57125,
                                "worksId": 676,
                                "number": 16,
                                "title": "016",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57126,
                                "worksId": 676,
                                "number": 17,
                                "title": "017",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57127,
                                "worksId": 676,
                                "number": 18,
                                "title": "018",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57128,
                                "worksId": 676,
                                "number": 19,
                                "title": "019",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57129,
                                "worksId": 676,
                                "number": 20,
                                "title": "020",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57130,
                                "worksId": 676,
                                "number": 21,
                                "title": "021",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57131,
                                "worksId": 676,
                                "number": 22,
                                "title": "022",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57132,
                                "worksId": 676,
                                "number": 23,
                                "title": "023",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57133,
                                "worksId": 676,
                                "number": 24,
                                "title": "024",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57133,
                                "worksId": 676,
                                "number": 24,
                                "title": "024",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57134,
                                "worksId": 676,
                                "number": 25,
                                "title": "025",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57135,
                                "worksId": 676,
                                "number": 26,
                                "title": "026",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57136,
                                "worksId": 676,
                                "number": 27,
                                "title": "027",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57137,
                                "worksId": 676,
                                "number": 28,
                                "title": "028",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57138,
                                "worksId": 676,
                                "number": 29,
                                "title": "029",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57139,
                                "worksId": 676,
                                "number": 30,
                                "title": "030",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57140,
                                "worksId": 676,
                                "number": 31,
                                "title": "031",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57141,
                                "worksId": 676,
                                "number": 32,
                                "title": "032",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57142,
                                "worksId": 676,
                                "number": 33,
                                "title": "033",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57143,
                                "worksId": 676,
                                "number": 34,
                                "title": "034",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57144,
                                "worksId": 676,
                                "number": 35,
                                "title": "035",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57145,
                                "worksId": 676,
                                "number": 36,
                                "title": "036",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57146,
                                "worksId": 676,
                                "number": 37,
                                "title": "037",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57147,
                                "worksId": 676,
                                "number": 38,
                                "title": "038",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57148,
                                "worksId": 676,
                                "number": 39,
                                "title": "039",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57149,
                                "worksId": 676,
                                "number": 40,
                                "title": "040",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57150,
                                "worksId": 676,
                                "number": 41,
                                "title": "041",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57151,
                                "worksId": 676,
                                "number": 42,
                                "title": "042",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57152,
                                "worksId": 676,
                                "number": 43,
                                "title": "043",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57153,
                                "worksId": 676,
                                "number": 44,
                                "title": "044",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                            {
                                "id": 57154,
                                "worksId": 676,
                                "number": 45,
                                "title": "045",
                                "coverUrl": "",
                                "intro": null,
                                "saleType": 4,
                                "isFreeTime": 0,
                                "freeTime": 0,
                                "price": 25,
                                "purchase": false,
                                "commentTotal": 0,
                                "duration": 85,
                                "playCount": 0,
                                "playUrl": null,
                                "worksTitle": null,
                                "worksIntro": null,
                                "collectTotal": 0,
                                "isCollect": 0,
                                "worksCoverUrl": null,
                                "captionsUrl": null,
                                "isSubtitles": 1,
                                "isLandscape": null,
                                "state": "serialize",
                                "isPlay": 0,
                                "isNewPlay": 0
                            },
                        ],
                        "isLandscape": 0
                    },
                    "extend": null
                }
                // 模拟成功情况
                resolve(data.data);
                // 模拟失败情况
                // reject('数据获取失败');
            }, 1000);
        });
    }

    const tempPromise = fetchData();

    useEffect(() => {
        tempPromise.then((data) => {
            console.log('成功：', data);
            setVideoDetailsData(data);
            setPageData(data);
            setCoverImage(data.coverUrl);
            const tempArray = new Array(data.dramaList.length).fill(false);
            setPageDataLock(tempArray);
            setSpinning(false);
        })
    }, []);

    return (
        <div className="details_box">
            <Spin spinning={spinning} fullscreen/>
            <div className="details_content">
                <div className="details_info_box">
                    <div className="box_l">
                        <div className="cover_box">
                            <Link to="/video">
                                <div className="image" style={{backgroundImage: 'url(' + coverImage + ')'}}></div>
                            </Link>
                        </div>
                    </div>
                    <div className="box_r">
                        <div className="name">
                            {
                                pageData ? pageData.title ? pageData.title : '' : ''
                            }
                        </div>
                        <div className="episodes">
                            Ended&nbsp;·&nbsp;
                            {
                                pageData ? pageData.dramaList.length > 0 ? pageData.dramaList.length : '' : ''
                            }
                            episodes
                        </div>
                        <div className="play_num">
                            Views：
                            {
                                pageData ? pageData.readTotal ? getNum(pageData.readTotal) : '' : ''
                            }
                        </div>
                        <div className="flexSB">
                            <Link to="/video">
                                <div className="btn_collect">
                                    {/*<PlusOutlined />*/}

                                    <span>
                                     &nbsp;Play&nbsp;
                                    </span>
                                </div>
                            </Link>
                            <div className="icon_share" onClick={() => handleShowModal()}>
                                <ShareAltOutlined/>
                            </div>
                        </div>
                    </div>

                </div>
                <div className="details_introduction_box">
                    {
                        pageData ? pageData.intro ? pageData.intro : '' : ''
                    }
                </div>
            </div>
            <div className="episode_box" style={{bottom: episode ? '-33vh' : '0'}}>
                <div className="episode_top_icon" onClick={() => switchEpisode()}>
                    {
                        episode
                            ? <CaretUpOutlined/>
                            : <CaretDownOutlined/>
                    }
                </div>
                <div className="episode_content" style={{overflow: episode ? 'hidden' : 'auto'}}>
                    <div className="episodesList_box">
                        {
                            pageData
                                ? pageData.dramaList.map((item, index) => (
                                    <div key={index}
                                       className="episodesList_item"
                                       onClick={() => HandleEpisodesRouterTo(index + 1, item.saleType)}
                                    >
                                        {index + 1}
                                        {/*{*/}
                                        {/*    item.saleType == 4*/}
                                        {/*        ? <div className="icon_lock">*/}
                                        {/*            <LockOutlined/>*/}
                                        {/*        </div>*/}
                                        {/*        : ''*/}
                                        {/*}*/}

                                    </div>
                                ))
                                : ''
                        }
                    </div>
                </div>
            </div>
            <ShareContainer isModalOpen={isModalOpen} setIsModalOpen={setIsModalOpen}></ShareContainer>
        </div>
    );
};

const mapStateToProps = (state) => {
    return {
        videoDetailsData: state.videoDetailsData.videoDetailsData,
    };
};

const mapDispatchToProps = (dispatch) => {
    return {
        setVideoDetailsData: (value) => dispatch({ type: 'SETDATA', data: value}),
    };
};

export default  connect(mapStateToProps, mapDispatchToProps)(Details);